# Generated by Django 3.1.3 on 2022-10-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20221007_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='correctness',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='text_content',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='grade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
